version: '3.9'
services:
  backend:
    build: .
    ports:
      - 8080:3000
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379



